apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpleapi

spec:
  replicas: 1
  selector:
    matchLabels:
      app: simpleapi
    template:
      metadata:
        labels:
          app: simpleapi
      spec:
        containers:
          - name: simpleapi
            image: docker_images/simpleapi
            ports:
              - containerPort: 9000
            readinessProbe:
              httpGet:
                path: /healthcheck
                port: 9000
              initialDelaySeconds: 10
              periodSeconds: 30
            resources:
              limits:
                cpu: 500m
                memory: 512Mi
              requests:
                cpu: 250m
                memory: 256Mi
